### ISSUE TITLE
Warnings when running cron job

### ISSUE THREAD

**Issue by jfbon** [disqus/disqus-wordpress#123]
Getting php warnings (php 7) when cron runs dsq_sync_forum...

```
2:50:49 wp_cron | 2016-10-18T10:49:12.20600  wp_cron:RUN (running_tasks=62, allowed_tasks=96, optimistic=1)
12:50:49 wp_cron | 2016-10-18T10:49:13.20672  PHP Warning: Creating default object from empty value in /wp-content/plugins/disqus-comment-system/disqus.php on line 749
12:50:49 wp_cron | 2016-10-18T10:49:13.20675  Warning: Creating default object from empty value in /wp-content/plugins/disqus-comment-system/disqus.php on line 749
12:50:49 wp_cron | 2016-10-18T10:49:13.20679  Executed the cron event 'dsq_sync_forum' in 0.013s.
```

**Comment by phh** [comment]
+1

```
PHP Fatal error:  Uncaught Error: Call to a member function update_thread() on null in /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php:807
Stack trace:
#0 /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php(733): dsq_update_permalink(Object(WP_Post))
#1 /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php(760): dsq_sync_post('93096')
#2 /var/www/.../wp/wp-includes/class-wp-hook.php(298): dsq_sync_forum()
#3 /var/www/.../wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 /var/www/.../wp/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#5 phar:///var/www/virtual/wp-cli/releases/1480494351/bin/wp/php/commands/cron-event.php(284): do_action_ref_array('dsq_sync_forum', Array)
#6 phar:///var/www/virtual/wp-cli/releases/ in /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php on line 807
```

**Comment by jsonUK** [comment]
Yup, seeing the same problem. Version 2.86.
Using wp-cli cron triggers error.

```
PHP Warning:  Creating default object from empty value in /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php on line 749
Warning: Creating default object from empty value in /var/www/.../wp-content/plugins/disqus-comment-system/disqus.php on line 749
```

**Comment by phh** [comment]
I've added a small plugin on my site to disable the cronjob:

```
<?php
/**
 * Disqus Fix Cron
 *
 * @author  Patrick Hesselberg
 *
 * Plugin Name:       Disqus Fix Cron
 * Plugin URI:
 * Description:       Disqus 'dsq_sync_forum' generates a fatal error. This plugin makes up for that error and stops disqus from scheduling this cron event.
 * Version:           0.1
 * Author:            Patrick Hesselberg
 * Author URI:        http://peytz.dk/medarbejdere/phh
 */
function dcf_disqus_fix_cron( $event ) {
	if ( $event->hook == 'dsq_sync_forum' ) {
		return false;
	}

	return $event;
}
add_filter( 'schedule_event', 'dcf_disqus_fix_cron' );
```

**Comment by dmatt** [comment]
We're working on some improvements to how the plugin handles syncing which should resolve this issue. In the meantime, if syncing is not a requirement for your site, you can disable the feature (similar to @phh's suggestion) within the plugin settings at Comments > Disqus > Sync > Disable automated comment importing.
